window:
  padding:
    x: 6
    y: 4
  dynamic_padding: true
  decorations: none
  startup_mode: Fullscreen
  title: Alacritty
  dynamic_title: false


scrolling:
  history: 0
  multiplier: 3


font:
  draw_bold_text_with_bright_colors: false

  normal:
    family: FiraCode
    style: Regular

  bold:
    family: FiraCode
    style: Bold

  italic:
    family: FiraCode
    style: Italic

  bold_italic:
    family: FiraCode
    style: Bold Italic

  size: 10.0

  offset:
    x: 0
    y: 2


colors:
  primary:
    background: '0xfdf6e3'
    foreground: '0x657b83'

  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'


mouse:
  hide_when_typing: true


window.opacity: 1.0
live_config_reload: true
