columns: 80
newline: native

steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: group
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: module_name
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true

  - trailing_whitespace: {}
