#!/bin/sh

filename=$(basename "$1")
filesize=$(du -Hh "$1" | cut -f 1)
geometry=$(identify -format '%wx%h' "$1[0]")
tags=$(exiv2 -q -P v -g "Iptc.Application2.Keywords" "$1" | tr '\n' ',')
tags=${tags%,}

echo "[${filesize}] <${geometry}${tags:+$s}${tags}> ${filename}"
