# Start graphical terminal emulator instance
gnome-terminal&

# Init special keys binding
xbindkeys&

# Configure appropriate laptop track pad delays and detections
syndaemon -t -k -i 1 -d &
# Hide mice cursor after 1 second
unclutter -idle 1 -jitter 2 -root&

# Use 'Caps Lock' key as both 'Control' and 'Esc' keys
setxkbmap -option ctrl:swapcaps
xcape -e 'Control_L=Escape'&
# Swap Super_R with Ctrl_R
setxkbmap -option ctrl:swap_rwin_rctl
# Set us-international-altgr keyboard
setxkbmap us -variant algr-intl
# User Super_L as AltGr
xmodmap ~/.xmodmaprc

# Config monitors and sound setup (Home or No-Home)
./.scripts/setup.sh

# Run ratpoison (window manager)
exec ratpoison
